version: '2'


volumenes:
  db-data:
   external: false

services:
 db:
   image: mysql
   env_file: .env
   volumes: 
    - db-data:/var/lib/mysql/db-data

 app:
   build: .
   env_file: -env
   volumes:
    - .:/usr/src/app
   ports:
    - "3000:3000"
   depends_on:
    - db
